import Foundation

struct VerseOfTheDayEntry {
    let dayOfYear: Int
    let bookName: String
    let chapter: Int
    let verse: Int
    let text: String
}

// 366 entries — one per day of the year (day 1 = Jan 1, day 366 = Dec 31 in leap year).
// Seasonal passages are anchored to the calendar; the rest are spread through well-known
// verses from across the Bible in a varied order.
let verseOfTheDayVerses: [VerseOfTheDayEntry] = [
    // ── January 1–7: New Year / New Beginnings ──────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 1, bookName: "Lamentations", chapter: 3, verse: 23, text: "They are new every morning: great is thy faithfulness."),
    VerseOfTheDayEntry(dayOfYear: 2, bookName: "Jeremiah", chapter: 29, verse: 11, text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end."),
    VerseOfTheDayEntry(dayOfYear: 3, bookName: "Isaiah", chapter: 43, verse: 19, text: "Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert."),
    VerseOfTheDayEntry(dayOfYear: 4, bookName: "Isaiah", chapter: 40, verse: 31, text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."),
    VerseOfTheDayEntry(dayOfYear: 5, bookName: "Romans", chapter: 12, verse: 2, text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God."),
    VerseOfTheDayEntry(dayOfYear: 6, bookName: "Philippians", chapter: 4, verse: 13, text: "I can do all things through Christ which strengtheneth me."),
    VerseOfTheDayEntry(dayOfYear: 7, bookName: "Joshua", chapter: 1, verse: 9, text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."),
    // ── January 8–31 ────────────────────────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 8, bookName: "Proverbs", chapter: 3, verse: 5, text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding."),
    VerseOfTheDayEntry(dayOfYear: 9, bookName: "Proverbs", chapter: 3, verse: 6, text: "In all thy ways acknowledge him, and he shall direct thy paths."),
    VerseOfTheDayEntry(dayOfYear: 10, bookName: "Matthew", chapter: 5, verse: 3, text: "Blessed are the poor in spirit: for theirs is the kingdom of heaven."),
    VerseOfTheDayEntry(dayOfYear: 11, bookName: "Psalms", chapter: 23, verse: 1, text: "The LORD is my shepherd; I shall not want."),
    VerseOfTheDayEntry(dayOfYear: 12, bookName: "John", chapter: 14, verse: 6, text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me."),
    VerseOfTheDayEntry(dayOfYear: 13, bookName: "Romans", chapter: 8, verse: 28, text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose."),
    // ── February 14: Love / Valentine's Day ─────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 14, bookName: "1 Corinthians", chapter: 13, verse: 4, text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,"),
    VerseOfTheDayEntry(dayOfYear: 15, bookName: "Song of Solomon", chapter: 8, verse: 7, text: "Many waters cannot quench love, neither can the floods drown it: if a man would give all the substance of his house for love, it would utterly be contemned."),
    VerseOfTheDayEntry(dayOfYear: 16, bookName: "1 John", chapter: 4, verse: 8, text: "He that loveth not knoweth not God; for God is love."),
    VerseOfTheDayEntry(dayOfYear: 17, bookName: "John", chapter: 15, verse: 12, text: "This is my commandment, That ye love one another, as I have loved you."),
    VerseOfTheDayEntry(dayOfYear: 18, bookName: "Deuteronomy", chapter: 31, verse: 6, text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee."),
    VerseOfTheDayEntry(dayOfYear: 19, bookName: "Psalms", chapter: 46, verse: 1, text: "God is our refuge and strength, a very present help in trouble."),
    VerseOfTheDayEntry(dayOfYear: 20, bookName: "Psalms", chapter: 27, verse: 1, text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?"),
    VerseOfTheDayEntry(dayOfYear: 21, bookName: "Isaiah", chapter: 41, verse: 10, text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness."),
    VerseOfTheDayEntry(dayOfYear: 22, bookName: "2 Timothy", chapter: 1, verse: 7, text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."),
    VerseOfTheDayEntry(dayOfYear: 23, bookName: "Ephesians", chapter: 2, verse: 8, text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:"),
    VerseOfTheDayEntry(dayOfYear: 24, bookName: "Romans", chapter: 5, verse: 8, text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us."),
    VerseOfTheDayEntry(dayOfYear: 25, bookName: "1 Peter", chapter: 5, verse: 7, text: "Casting all your care upon him; for he careth for you."),
    VerseOfTheDayEntry(dayOfYear: 26, bookName: "Matthew", chapter: 11, verse: 28, text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest."),
    VerseOfTheDayEntry(dayOfYear: 27, bookName: "Psalms", chapter: 119, verse: 105, text: "Thy word is a lamp unto my feet, and a light unto my path."),
    VerseOfTheDayEntry(dayOfYear: 28, bookName: "John", chapter: 8, verse: 12, text: "Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life."),
    VerseOfTheDayEntry(dayOfYear: 29, bookName: "Galatians", chapter: 5, verse: 22, text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,"),
    VerseOfTheDayEntry(dayOfYear: 30, bookName: "Colossians", chapter: 3, verse: 23, text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;"),
    VerseOfTheDayEntry(dayOfYear: 31, bookName: "Genesis", chapter: 1, verse: 1, text: "In the beginning God created the heaven and the earth."),
    // ── February ─────────────────────────────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 32, bookName: "Psalms", chapter: 1, verse: 1, text: "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful."),
    VerseOfTheDayEntry(dayOfYear: 33, bookName: "Psalms", chapter: 1, verse: 3, text: "And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper."),
    VerseOfTheDayEntry(dayOfYear: 34, bookName: "Matthew", chapter: 6, verse: 33, text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."),
    VerseOfTheDayEntry(dayOfYear: 35, bookName: "Romans", chapter: 1, verse: 16, text: "For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth; to the Jew first, and also to the Greek."),
    VerseOfTheDayEntry(dayOfYear: 36, bookName: "Philippians", chapter: 2, verse: 3, text: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves."),
    VerseOfTheDayEntry(dayOfYear: 37, bookName: "Ephesians", chapter: 4, verse: 32, text: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you."),
    VerseOfTheDayEntry(dayOfYear: 38, bookName: "Colossians", chapter: 1, verse: 16, text: "For by him were all things created, that are in heaven, and that are in earth, visible and invisible, whether they be thrones, or dominions, or principalities, or powers: all things were created by him, and for him:"),
    VerseOfTheDayEntry(dayOfYear: 39, bookName: "Hebrews", chapter: 11, verse: 1, text: "Now faith is the substance of things hoped for, the evidence of things not seen."),
    VerseOfTheDayEntry(dayOfYear: 40, bookName: "Hebrews", chapter: 11, verse: 6, text: "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him."),
    VerseOfTheDayEntry(dayOfYear: 41, bookName: "James", chapter: 1, verse: 5, text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him."),
    VerseOfTheDayEntry(dayOfYear: 42, bookName: "James", chapter: 2, verse: 17, text: "Even so faith, if it hath not works, is dead, being alone."),
    VerseOfTheDayEntry(dayOfYear: 43, bookName: "1 Thessalonians", chapter: 5, verse: 16, text: "Rejoice evermore."),
    VerseOfTheDayEntry(dayOfYear: 44, bookName: "1 Thessalonians", chapter: 5, verse: 17, text: "Pray without ceasing."),
    VerseOfTheDayEntry(dayOfYear: 45, bookName: "1 Thessalonians", chapter: 5, verse: 18, text: "In every thing give thanks: for this is the will of God in Christ Jesus concerning you."),
    VerseOfTheDayEntry(dayOfYear: 46, bookName: "Proverbs", chapter: 16, verse: 3, text: "Commit thy works unto the LORD, and thy thoughts shall be established."),
    VerseOfTheDayEntry(dayOfYear: 47, bookName: "Proverbs", chapter: 16, verse: 9, text: "A man's heart deviseth his way: but the LORD directeth his steps."),
    VerseOfTheDayEntry(dayOfYear: 48, bookName: "Proverbs", chapter: 17, verse: 17, text: "A friend loveth at all times, and a brother is born for adversity."),
    VerseOfTheDayEntry(dayOfYear: 49, bookName: "Proverbs", chapter: 18, verse: 24, text: "A man that hath friends must shew himself friendly: and there is a friend that sticketh closer than a brother."),
    VerseOfTheDayEntry(dayOfYear: 50, bookName: "Proverbs", chapter: 22, verse: 6, text: "Train up a child in the way he should go: and when he is old, he will not depart from it."),
    VerseOfTheDayEntry(dayOfYear: 51, bookName: "Proverbs", chapter: 31, verse: 25, text: "Strength and honour are her clothing; and she shall rejoice in time to come."),
    VerseOfTheDayEntry(dayOfYear: 52, bookName: "Ecclesiastes", chapter: 3, verse: 1, text: "To every thing there is a season, and a time to every purpose under the heaven:"),
    VerseOfTheDayEntry(dayOfYear: 53, bookName: "Ecclesiastes", chapter: 3, verse: 11, text: "He hath made every thing beautiful in his time: also he hath set the world in their heart, so that no man can find out the work that God maketh from the beginning to the end."),
    VerseOfTheDayEntry(dayOfYear: 54, bookName: "Matthew", chapter: 5, verse: 8, text: "Blessed are the pure in heart: for they shall see God."),
    VerseOfTheDayEntry(dayOfYear: 55, bookName: "Matthew", chapter: 5, verse: 9, text: "Blessed are the peacemakers: for they shall be called the children of God."),
    VerseOfTheDayEntry(dayOfYear: 56, bookName: "Luke", chapter: 6, verse: 27, text: "But I say unto you which hear, Love your enemies, do good to them which hate you,"),
    VerseOfTheDayEntry(dayOfYear: 57, bookName: "Luke", chapter: 6, verse: 38, text: "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom."),
    VerseOfTheDayEntry(dayOfYear: 58, bookName: "Acts", chapter: 1, verse: 8, text: "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth."),
    VerseOfTheDayEntry(dayOfYear: 59, bookName: "Acts", chapter: 2, verse: 38, text: "Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost."),
    // ── March ────────────────────────────────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 60, bookName: "Romans", chapter: 3, verse: 23, text: "For all have sinned, and come short of the glory of God;"),
    VerseOfTheDayEntry(dayOfYear: 61, bookName: "Romans", chapter: 3, verse: 24, text: "Being justified freely by his grace through the redemption that is in Christ Jesus:"),
    VerseOfTheDayEntry(dayOfYear: 62, bookName: "Romans", chapter: 6, verse: 23, text: "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord."),
    VerseOfTheDayEntry(dayOfYear: 63, bookName: "Romans", chapter: 10, verse: 9, text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved."),
    VerseOfTheDayEntry(dayOfYear: 64, bookName: "Romans", chapter: 10, verse: 17, text: "So then faith cometh by hearing, and hearing by the word of God."),
    VerseOfTheDayEntry(dayOfYear: 65, bookName: "1 Corinthians", chapter: 1, verse: 18, text: "For the preaching of the cross is to them that perish foolishness; but unto us which are saved it is the power of God."),
    VerseOfTheDayEntry(dayOfYear: 66, bookName: "1 Corinthians", chapter: 2, verse: 9, text: "But as it is written, Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him."),
    VerseOfTheDayEntry(dayOfYear: 67, bookName: "2 Corinthians", chapter: 5, verse: 17, text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new."),
    VerseOfTheDayEntry(dayOfYear: 68, bookName: "2 Corinthians", chapter: 12, verse: 9, text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness."),
    VerseOfTheDayEntry(dayOfYear: 69, bookName: "Galatians", chapter: 2, verse: 20, text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me."),
    VerseOfTheDayEntry(dayOfYear: 70, bookName: "Ephesians", chapter: 1, verse: 7, text: "In whom we have redemption through his blood, the forgiveness of sins, according to the riches of his grace;"),
    VerseOfTheDayEntry(dayOfYear: 71, bookName: "Ephesians", chapter: 3, verse: 20, text: "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us,"),
    VerseOfTheDayEntry(dayOfYear: 72, bookName: "Philippians", chapter: 3, verse: 14, text: "I press toward the mark for the prize of the high calling of God in Christ Jesus."),
    VerseOfTheDayEntry(dayOfYear: 73, bookName: "Philippians", chapter: 4, verse: 6, text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God."),
    VerseOfTheDayEntry(dayOfYear: 74, bookName: "Philippians", chapter: 4, verse: 7, text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus."),
    VerseOfTheDayEntry(dayOfYear: 75, bookName: "Philippians", chapter: 4, verse: 19, text: "But my God shall supply all your need according to his riches in glory by Christ Jesus."),
    VerseOfTheDayEntry(dayOfYear: 76, bookName: "Colossians", chapter: 3, verse: 16, text: "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord."),
    VerseOfTheDayEntry(dayOfYear: 77, bookName: "2 Timothy", chapter: 3, verse: 16, text: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness:"),
    VerseOfTheDayEntry(dayOfYear: 78, bookName: "Hebrews", chapter: 4, verse: 12, text: "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart."),
    VerseOfTheDayEntry(dayOfYear: 79, bookName: "Hebrews", chapter: 4, verse: 16, text: "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need."),
    VerseOfTheDayEntry(dayOfYear: 80, bookName: "Hebrews", chapter: 12, verse: 1, text: "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us,"),
    VerseOfTheDayEntry(dayOfYear: 81, bookName: "Hebrews", chapter: 12, verse: 2, text: "Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God."),
    VerseOfTheDayEntry(dayOfYear: 82, bookName: "James", chapter: 4, verse: 7, text: "Submit yourselves therefore to God. Resist the devil, and he will flee from you."),
    VerseOfTheDayEntry(dayOfYear: 83, bookName: "1 Peter", chapter: 2, verse: 9, text: "But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light:"),
    VerseOfTheDayEntry(dayOfYear: 84, bookName: "1 Peter", chapter: 3, verse: 15, text: "But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear:"),
    // ── Late March – Mid April: Holy Week / Passion / Resurrection ───────────────
    VerseOfTheDayEntry(dayOfYear: 85, bookName: "Isaiah", chapter: 53, verse: 5, text: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed."),
    VerseOfTheDayEntry(dayOfYear: 86, bookName: "Isaiah", chapter: 53, verse: 6, text: "All we like sheep have gone astray; we have turned every one to his own way; and the LORD hath laid on him the iniquity of us all."),
    VerseOfTheDayEntry(dayOfYear: 87, bookName: "Zechariah", chapter: 9, verse: 9, text: "Rejoice greatly, O daughter of Zion; shout, O daughter of Jerusalem: behold, thy King cometh unto thee: he is just, and having salvation; lowly, and riding upon an ass, and upon a colt the foal of an ass."),
    VerseOfTheDayEntry(dayOfYear: 88, bookName: "Psalms", chapter: 22, verse: 1, text: "My God, my God, why hast thou forsaken me? why art thou so far from helping me, and from the words of my roaring?"),
    VerseOfTheDayEntry(dayOfYear: 89, bookName: "Psalms", chapter: 22, verse: 16, text: "For dogs have compassed me: the assembly of the wicked have inclosed me: they pierced my hands and my feet."),
    VerseOfTheDayEntry(dayOfYear: 90, bookName: "Mark", chapter: 10, verse: 45, text: "For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many."),
    VerseOfTheDayEntry(dayOfYear: 91, bookName: "John", chapter: 12, verse: 24, text: "Verily, verily, I say unto you, Except a corn of wheat fall into the ground and die, it abideth alone: but if it die, it bringeth forth much fruit."),
    VerseOfTheDayEntry(dayOfYear: 92, bookName: "Luke", chapter: 22, verse: 19, text: "And he took bread, and gave thanks, and brake it, and gave unto them, saying, This is my body which is given for you: this do in remembrance of me."),
    VerseOfTheDayEntry(dayOfYear: 93, bookName: "Luke", chapter: 22, verse: 42, text: "Saying, Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done."),
    VerseOfTheDayEntry(dayOfYear: 94, bookName: "John", chapter: 15, verse: 13, text: "Greater love hath no man than this, that a man lay down his life for his friends."),
    VerseOfTheDayEntry(dayOfYear: 95, bookName: "John", chapter: 19, verse: 30, text: "When Jesus therefore had received the vinegar, he said, It is finished: and he bowed his head, and gave up the ghost."),
    VerseOfTheDayEntry(dayOfYear: 96, bookName: "Matthew", chapter: 27, verse: 46, text: "And about the ninth hour Jesus cried with a loud voice, saying, Eli, Eli, lama sabachthani? that is to say, My God, my God, why hast thou forsaken me?"),
    VerseOfTheDayEntry(dayOfYear: 97, bookName: "Luke", chapter: 23, verse: 34, text: "Then said Jesus, Father, forgive them; for they know not what they do."),
    VerseOfTheDayEntry(dayOfYear: 98, bookName: "Luke", chapter: 23, verse: 43, text: "And Jesus said unto him, Verily I say unto thee, To day shalt thou be with me in paradise."),
    VerseOfTheDayEntry(dayOfYear: 99, bookName: "Mark", chapter: 16, verse: 6, text: "And he saith unto them, Be not affrighted: Ye seek Jesus of Nazareth, which was crucified: he is risen; he is not here: behold the place where they laid him."),
    VerseOfTheDayEntry(dayOfYear: 100, bookName: "John", chapter: 3, verse: 16, text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."),
    VerseOfTheDayEntry(dayOfYear: 101, bookName: "John", chapter: 11, verse: 25, text: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live:"),
    VerseOfTheDayEntry(dayOfYear: 102, bookName: "Romans", chapter: 8, verse: 11, text: "But if the Spirit of him that raised up Jesus from the dead dwell in you, he that raised up Christ from the dead shall also quicken your mortal bodies by his Spirit that dwelleth in you."),
    VerseOfTheDayEntry(dayOfYear: 103, bookName: "1 Corinthians", chapter: 15, verse: 3, text: "For I delivered unto you first of all that which I also received, how that Christ died for our sins according to the scriptures;"),
    VerseOfTheDayEntry(dayOfYear: 104, bookName: "1 Corinthians", chapter: 15, verse: 4, text: "And that he was buried, and that he rose again the third day according to the scriptures:"),
    VerseOfTheDayEntry(dayOfYear: 105, bookName: "1 Corinthians", chapter: 15, verse: 55, text: "O death, where is thy sting? O grave, where is thy victory?"),
    // ── Late April – May: Spring / Growth / God's Provision ──────────────────────
    VerseOfTheDayEntry(dayOfYear: 106, bookName: "Psalms", chapter: 92, verse: 12, text: "The righteous shall flourish like the palm tree: he shall grow like a cedar in Lebanon."),
    VerseOfTheDayEntry(dayOfYear: 107, bookName: "Song of Solomon", chapter: 2, verse: 11, text: "For, lo, the winter is past, the rain is over and gone;"),
    VerseOfTheDayEntry(dayOfYear: 108, bookName: "Matthew", chapter: 6, verse: 26, text: "Behold the fowls of the air: for they sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?"),
    VerseOfTheDayEntry(dayOfYear: 109, bookName: "Matthew", chapter: 6, verse: 28, text: "And why take ye thought for raiment? Consider the lilies of the field, how they grow; they toil not, neither do they spin:"),
    VerseOfTheDayEntry(dayOfYear: 110, bookName: "Matthew", chapter: 13, verse: 23, text: "But he that received seed into the good ground is he that heareth the word, and understandeth it; which also beareth fruit, and bringeth forth, some an hundredfold, some sixty, some thirty."),
    VerseOfTheDayEntry(dayOfYear: 111, bookName: "Mark", chapter: 4, verse: 27, text: "And should sleep, and rise night and day, and the seed should spring and grow up, he knoweth not how."),
    VerseOfTheDayEntry(dayOfYear: 112, bookName: "John", chapter: 15, verse: 5, text: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing."),
    VerseOfTheDayEntry(dayOfYear: 113, bookName: "John", chapter: 15, verse: 16, text: "Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit, and that your fruit should remain: that whatsoever ye shall ask of the Father in my name, he may give it you."),
    VerseOfTheDayEntry(dayOfYear: 114, bookName: "Galatians", chapter: 6, verse: 9, text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not."),
    VerseOfTheDayEntry(dayOfYear: 115, bookName: "Galatians", chapter: 6, verse: 7, text: "Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap."),
    VerseOfTheDayEntry(dayOfYear: 116, bookName: "James", chapter: 1, verse: 17, text: "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning."),
    VerseOfTheDayEntry(dayOfYear: 117, bookName: "Psalms", chapter: 65, verse: 11, text: "Thou crownest the year with thy goodness; and thy paths drop fatness."),
    VerseOfTheDayEntry(dayOfYear: 118, bookName: "Psalms", chapter: 104, verse: 24, text: "O LORD, how manifold are thy works! in wisdom hast thou made them all: the earth is full of thy riches."),
    VerseOfTheDayEntry(dayOfYear: 119, bookName: "Psalms", chapter: 139, verse: 14, text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well."),
    VerseOfTheDayEntry(dayOfYear: 120, bookName: "Psalms", chapter: 139, verse: 13, text: "For thou hast possessed my reins: thou hast covered me in my mother's womb."),
    VerseOfTheDayEntry(dayOfYear: 121, bookName: "Proverbs", chapter: 4, verse: 23, text: "Keep thy heart with all diligence; for out of it are the issues of life."),
    VerseOfTheDayEntry(dayOfYear: 122, bookName: "Proverbs", chapter: 12, verse: 25, text: "Heaviness in the heart of man maketh it stoop: but a good word maketh it glad."),
    VerseOfTheDayEntry(dayOfYear: 123, bookName: "Isaiah", chapter: 58, verse: 11, text: "And the LORD shall guide thee continually, and satisfy thy soul in drought, and make fat thy bones: and thou shalt be like a watered garden, and like a spring of water, whose waters fail not."),
    VerseOfTheDayEntry(dayOfYear: 124, bookName: "Jeremiah", chapter: 31, verse: 3, text: "The LORD hath appeared of old unto me, saying, Yea, I have loved thee with an everlasting love: therefore with lovingkindness have I drawn thee."),
    VerseOfTheDayEntry(dayOfYear: 125, bookName: "Zephaniah", chapter: 3, verse: 17, text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing."),
    VerseOfTheDayEntry(dayOfYear: 126, bookName: "Matthew", chapter: 5, verse: 14, text: "Ye are the light of the world. A city that is set on an hill cannot be hid."),
    VerseOfTheDayEntry(dayOfYear: 127, bookName: "Matthew", chapter: 5, verse: 16, text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven."),
    VerseOfTheDayEntry(dayOfYear: 128, bookName: "Matthew", chapter: 7, verse: 7, text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:"),
    VerseOfTheDayEntry(dayOfYear: 129, bookName: "Matthew", chapter: 7, verse: 12, text: "Therefore all things whatsoever ye would that men should do to you, do ye even so to them: for this is the law and the prophets."),
    VerseOfTheDayEntry(dayOfYear: 130, bookName: "Luke", chapter: 12, verse: 7, text: "But even the very hairs of your head are all numbered. Fear not therefore: ye are of more value than many sparrows."),
    VerseOfTheDayEntry(dayOfYear: 131, bookName: "John", chapter: 10, verse: 11, text: "I am the good shepherd: the good shepherd giveth his life for the sheep."),
    VerseOfTheDayEntry(dayOfYear: 132, bookName: "John", chapter: 10, verse: 14, text: "I am the good shepherd, and know my sheep, and am known of mine."),
    VerseOfTheDayEntry(dayOfYear: 133, bookName: "John", chapter: 10, verse: 28, text: "And I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand."),
    VerseOfTheDayEntry(dayOfYear: 134, bookName: "John", chapter: 16, verse: 33, text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world."),
    VerseOfTheDayEntry(dayOfYear: 135, bookName: "Acts", chapter: 4, verse: 12, text: "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved."),
    VerseOfTheDayEntry(dayOfYear: 136, bookName: "Acts", chapter: 16, verse: 31, text: "And they said, Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house."),
    VerseOfTheDayEntry(dayOfYear: 137, bookName: "Romans", chapter: 8, verse: 1, text: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit."),
    VerseOfTheDayEntry(dayOfYear: 138, bookName: "Romans", chapter: 8, verse: 38, text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,"),
    VerseOfTheDayEntry(dayOfYear: 139, bookName: "Romans", chapter: 8, verse: 39, text: "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord."),
    VerseOfTheDayEntry(dayOfYear: 140, bookName: "1 Corinthians", chapter: 10, verse: 13, text: "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it."),
    VerseOfTheDayEntry(dayOfYear: 141, bookName: "2 Corinthians", chapter: 4, verse: 17, text: "For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory;"),
    VerseOfTheDayEntry(dayOfYear: 142, bookName: "2 Corinthians", chapter: 4, verse: 18, text: "While we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal."),
    VerseOfTheDayEntry(dayOfYear: 143, bookName: "Ephesians", chapter: 6, verse: 10, text: "Finally, my brethren, be strong in the Lord, and in the power of his might."),
    VerseOfTheDayEntry(dayOfYear: 144, bookName: "Ephesians", chapter: 6, verse: 11, text: "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil."),
    VerseOfTheDayEntry(dayOfYear: 145, bookName: "Philippians", chapter: 1, verse: 6, text: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:"),
    VerseOfTheDayEntry(dayOfYear: 146, bookName: "Colossians", chapter: 2, verse: 6, text: "As ye have therefore received Christ Jesus the Lord, so walk ye in him:"),
    VerseOfTheDayEntry(dayOfYear: 147, bookName: "Colossians", chapter: 3, verse: 1, text: "If ye then be risen with Christ, seek those things which are above, where Christ sitteth on the right hand of God."),
    VerseOfTheDayEntry(dayOfYear: 148, bookName: "1 Thessalonians", chapter: 4, verse: 17, text: "Then we which are alive and remain shall be caught up together with them in the clouds, to meet the Lord in the air: and so shall we ever be with the Lord."),
    VerseOfTheDayEntry(dayOfYear: 149, bookName: "1 Timothy", chapter: 6, verse: 6, text: "But godliness with contentment is great gain."),
    VerseOfTheDayEntry(dayOfYear: 150, bookName: "1 Timothy", chapter: 6, verse: 12, text: "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast professed a good profession before many witnesses."),
    VerseOfTheDayEntry(dayOfYear: 151, bookName: "Titus", chapter: 3, verse: 5, text: "Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost;"),
    // ── June: Psalms ─────────────────────────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 152, bookName: "Psalms", chapter: 16, verse: 11, text: "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore."),
    VerseOfTheDayEntry(dayOfYear: 153, bookName: "Psalms", chapter: 19, verse: 1, text: "The heavens declare the glory of God; and the firmament sheweth his handywork."),
    VerseOfTheDayEntry(dayOfYear: 154, bookName: "Psalms", chapter: 19, verse: 14, text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer."),
    VerseOfTheDayEntry(dayOfYear: 155, bookName: "Psalms", chapter: 23, verse: 2, text: "He maketh me to lie down in green pastures: he leadeth me beside the still waters."),
    VerseOfTheDayEntry(dayOfYear: 156, bookName: "Psalms", chapter: 23, verse: 3, text: "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake."),
    VerseOfTheDayEntry(dayOfYear: 157, bookName: "Psalms", chapter: 23, verse: 4, text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me."),
    VerseOfTheDayEntry(dayOfYear: 158, bookName: "Psalms", chapter: 23, verse: 6, text: "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever."),
    VerseOfTheDayEntry(dayOfYear: 159, bookName: "Psalms", chapter: 27, verse: 14, text: "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD."),
    VerseOfTheDayEntry(dayOfYear: 160, bookName: "Psalms", chapter: 29, verse: 11, text: "The LORD will give strength unto his people; the LORD will bless his people with peace."),
    VerseOfTheDayEntry(dayOfYear: 161, bookName: "Psalms", chapter: 30, verse: 5, text: "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning."),
    VerseOfTheDayEntry(dayOfYear: 162, bookName: "Psalms", chapter: 31, verse: 3, text: "For thou art my rock and my fortress; therefore for thy name's sake lead me, and guide me."),
    VerseOfTheDayEntry(dayOfYear: 163, bookName: "Psalms", chapter: 32, verse: 7, text: "Thou art my hiding place; thou shalt preserve me from trouble; thou shalt compass me about with songs of deliverance. Selah."),
    VerseOfTheDayEntry(dayOfYear: 164, bookName: "Psalms", chapter: 34, verse: 1, text: "I will bless the LORD at all times: his praise shall continually be in my mouth."),
    VerseOfTheDayEntry(dayOfYear: 165, bookName: "Psalms", chapter: 34, verse: 8, text: "O taste and see that the LORD is good: blessed is the man that trusteth in him."),
    VerseOfTheDayEntry(dayOfYear: 166, bookName: "Psalms", chapter: 34, verse: 18, text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit."),
    VerseOfTheDayEntry(dayOfYear: 167, bookName: "Psalms", chapter: 37, verse: 4, text: "Delight thyself also in the LORD: and he shall give thee the desires of thine heart."),
    VerseOfTheDayEntry(dayOfYear: 168, bookName: "Psalms", chapter: 37, verse: 5, text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass."),
    VerseOfTheDayEntry(dayOfYear: 169, bookName: "Psalms", chapter: 40, verse: 1, text: "I waited patiently for the LORD; and he inclined unto me, and heard my cry."),
    VerseOfTheDayEntry(dayOfYear: 170, bookName: "Psalms", chapter: 40, verse: 2, text: "He brought me up also out of an horrible pit, out of the miry clay, and set my feet upon a rock, and established my goings."),
    VerseOfTheDayEntry(dayOfYear: 171, bookName: "Psalms", chapter: 42, verse: 1, text: "As the hart panteth after the water brooks, so panteth my soul after thee, O God."),
    VerseOfTheDayEntry(dayOfYear: 172, bookName: "Psalms", chapter: 46, verse: 10, text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth."),
    VerseOfTheDayEntry(dayOfYear: 173, bookName: "Psalms", chapter: 51, verse: 10, text: "Create in me a clean heart, O God; and renew a right spirit within me."),
    VerseOfTheDayEntry(dayOfYear: 174, bookName: "Psalms", chapter: 55, verse: 22, text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved."),
    VerseOfTheDayEntry(dayOfYear: 175, bookName: "Psalms", chapter: 56, verse: 3, text: "What time I am afraid, I will trust in thee."),
    VerseOfTheDayEntry(dayOfYear: 176, bookName: "Psalms", chapter: 62, verse: 8, text: "Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us. Selah."),
    VerseOfTheDayEntry(dayOfYear: 177, bookName: "Psalms", chapter: 63, verse: 1, text: "O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;"),
    VerseOfTheDayEntry(dayOfYear: 178, bookName: "Psalms", chapter: 68, verse: 19, text: "Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation. Selah."),
    VerseOfTheDayEntry(dayOfYear: 179, bookName: "Psalms", chapter: 71, verse: 5, text: "For thou art my hope, O Lord GOD: thou art my trust from my youth."),
    VerseOfTheDayEntry(dayOfYear: 180, bookName: "Psalms", chapter: 73, verse: 26, text: "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever."),
    VerseOfTheDayEntry(dayOfYear: 181, bookName: "Psalms", chapter: 84, verse: 11, text: "For the LORD God is a sun and shield: the LORD will give grace and glory: no good thing will he withhold from them that walk uprightly."),
    // ── July: More Psalms / Trust ─────────────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 182, bookName: "Psalms", chapter: 86, verse: 15, text: "But thou, O Lord, art a God full of compassion, and gracious, longsuffering, and plenteous in mercy and truth."),
    VerseOfTheDayEntry(dayOfYear: 183, bookName: "Psalms", chapter: 90, verse: 2, text: "Before the mountains were brought forth, or ever thou hadst formed the earth and the world, even from everlasting to everlasting, thou art God."),
    VerseOfTheDayEntry(dayOfYear: 184, bookName: "Psalms", chapter: 91, verse: 1, text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty."),
    VerseOfTheDayEntry(dayOfYear: 185, bookName: "Psalms", chapter: 91, verse: 2, text: "I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust."),
    VerseOfTheDayEntry(dayOfYear: 186, bookName: "Psalms", chapter: 91, verse: 4, text: "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler."),
    VerseOfTheDayEntry(dayOfYear: 187, bookName: "Psalms", chapter: 91, verse: 11, text: "For he shall give his angels charge over thee, to keep thee in all thy ways."),
    VerseOfTheDayEntry(dayOfYear: 188, bookName: "Psalms", chapter: 94, verse: 19, text: "In the multitude of my thoughts within me thy comforts delight my soul."),
    VerseOfTheDayEntry(dayOfYear: 189, bookName: "Psalms", chapter: 100, verse: 1, text: "Make a joyful noise unto the LORD, all ye lands."),
    VerseOfTheDayEntry(dayOfYear: 190, bookName: "Psalms", chapter: 100, verse: 3, text: "Know ye that the LORD he is God: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture."),
    VerseOfTheDayEntry(dayOfYear: 191, bookName: "Psalms", chapter: 100, verse: 5, text: "For the LORD is good; his mercy is everlasting; and his truth endureth to all generations."),
    VerseOfTheDayEntry(dayOfYear: 192, bookName: "Psalms", chapter: 103, verse: 1, text: "Bless the LORD, O my soul: and all that is within me, bless his holy name."),
    VerseOfTheDayEntry(dayOfYear: 193, bookName: "Psalms", chapter: 103, verse: 3, text: "Who forgiveth all thine iniquities; who healeth all thy diseases;"),
    VerseOfTheDayEntry(dayOfYear: 194, bookName: "Psalms", chapter: 103, verse: 13, text: "Like as a father pitieth his children, so the LORD pitieth them that fear him."),
    VerseOfTheDayEntry(dayOfYear: 195, bookName: "Psalms", chapter: 107, verse: 9, text: "For he satisfieth the longing soul, and filleth the hungry soul with goodness."),
    VerseOfTheDayEntry(dayOfYear: 196, bookName: "Psalms", chapter: 112, verse: 7, text: "He shall not be afraid of evil tidings: his heart is fixed, trusting in the LORD."),
    VerseOfTheDayEntry(dayOfYear: 197, bookName: "Psalms", chapter: 116, verse: 1, text: "I love the LORD, because he hath heard my voice and my supplications."),
    VerseOfTheDayEntry(dayOfYear: 198, bookName: "Psalms", chapter: 118, verse: 24, text: "This is the day which the LORD hath made; we will rejoice and be glad in it."),
    VerseOfTheDayEntry(dayOfYear: 199, bookName: "Psalms", chapter: 119, verse: 9, text: "Wherewithal shall a young man cleanse his way? by taking heed thereto according to thy word."),
    VerseOfTheDayEntry(dayOfYear: 200, bookName: "Psalms", chapter: 119, verse: 11, text: "Thy word have I hid in mine heart, that I might not sin against thee."),
    VerseOfTheDayEntry(dayOfYear: 201, bookName: "Psalms", chapter: 119, verse: 130, text: "The entrance of thy words giveth light; it giveth understanding unto the simple."),
    VerseOfTheDayEntry(dayOfYear: 202, bookName: "Psalms", chapter: 121, verse: 1, text: "I will lift up mine eyes unto the hills, from whence cometh my help."),
    VerseOfTheDayEntry(dayOfYear: 203, bookName: "Psalms", chapter: 121, verse: 2, text: "My help cometh from the LORD, which made heaven and earth."),
    VerseOfTheDayEntry(dayOfYear: 204, bookName: "Psalms", chapter: 121, verse: 7, text: "The LORD shall preserve thee from all evil: he shall preserve thy soul."),
    VerseOfTheDayEntry(dayOfYear: 205, bookName: "Psalms", chapter: 121, verse: 8, text: "The LORD shall preserve thy going out and thy coming in from this time forth, and even for evermore."),
    VerseOfTheDayEntry(dayOfYear: 206, bookName: "Psalms", chapter: 127, verse: 1, text: "Except the LORD build the house, they labour in vain that build it: except the LORD keep the city, the watchman waketh but in vain."),
    VerseOfTheDayEntry(dayOfYear: 207, bookName: "Psalms", chapter: 130, verse: 3, text: "If thou, LORD, shouldest mark iniquities, O Lord, who shall stand?"),
    VerseOfTheDayEntry(dayOfYear: 208, bookName: "Psalms", chapter: 130, verse: 7, text: "Let Israel hope in the LORD: for with the LORD there is mercy, and with him is plenteous redemption."),
    VerseOfTheDayEntry(dayOfYear: 209, bookName: "Psalms", chapter: 133, verse: 1, text: "Behold, how good and how pleasant it is for brethren to dwell together in unity!"),
    VerseOfTheDayEntry(dayOfYear: 210, bookName: "Psalms", chapter: 139, verse: 7, text: "Whither shall I go from thy spirit? or whither shall I flee from thy presence?"),
    VerseOfTheDayEntry(dayOfYear: 211, bookName: "Psalms", chapter: 139, verse: 16, text: "Thine eyes did see my substance, yet being unperfect; and in thy book all my members were written, which in continuance were fashioned, when as yet there was none of them."),
    VerseOfTheDayEntry(dayOfYear: 212, bookName: "Psalms", chapter: 143, verse: 10, text: "Teach me to do thy will; for thou art my God: thy spirit is good; lead me into the land of uprightness."),
    // ── August: Proverbs / Wisdom ─────────────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 213, bookName: "Psalms", chapter: 145, verse: 3, text: "Great is the LORD, and greatly to be praised; and his greatness is unsearchable."),
    VerseOfTheDayEntry(dayOfYear: 214, bookName: "Psalms", chapter: 145, verse: 18, text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth."),
    VerseOfTheDayEntry(dayOfYear: 215, bookName: "Psalms", chapter: 147, verse: 3, text: "He healeth the broken in heart, and bindeth up their wounds."),
    VerseOfTheDayEntry(dayOfYear: 216, bookName: "Psalms", chapter: 150, verse: 6, text: "Let every thing that hath breath praise the LORD. Praise ye the LORD."),
    VerseOfTheDayEntry(dayOfYear: 217, bookName: "Proverbs", chapter: 1, verse: 7, text: "The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction."),
    VerseOfTheDayEntry(dayOfYear: 218, bookName: "Proverbs", chapter: 2, verse: 6, text: "For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding."),
    VerseOfTheDayEntry(dayOfYear: 219, bookName: "Proverbs", chapter: 3, verse: 7, text: "Be not wise in thine own eyes: fear the LORD, and depart from evil."),
    VerseOfTheDayEntry(dayOfYear: 220, bookName: "Proverbs", chapter: 4, verse: 7, text: "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding."),
    VerseOfTheDayEntry(dayOfYear: 221, bookName: "Proverbs", chapter: 10, verse: 12, text: "Hatred stirreth up strifes: but love covereth all sins."),
    VerseOfTheDayEntry(dayOfYear: 222, bookName: "Proverbs", chapter: 11, verse: 2, text: "When pride cometh, then cometh shame: but with the lowly is wisdom."),
    VerseOfTheDayEntry(dayOfYear: 223, bookName: "Proverbs", chapter: 11, verse: 14, text: "Where no counsel is, the people fall: but in the multitude of counsellors there is safety."),
    VerseOfTheDayEntry(dayOfYear: 224, bookName: "Proverbs", chapter: 12, verse: 1, text: "Whoso loveth instruction loveth knowledge: but he that hateth reproof is brutish."),
    VerseOfTheDayEntry(dayOfYear: 225, bookName: "Proverbs", chapter: 13, verse: 20, text: "He that walketh with wise men shall be wise: but a companion of fools shall be destroyed."),
    VerseOfTheDayEntry(dayOfYear: 226, bookName: "Proverbs", chapter: 14, verse: 12, text: "There is a way which seemeth right unto a man, but the end thereof are the ways of death."),
    VerseOfTheDayEntry(dayOfYear: 227, bookName: "Proverbs", chapter: 15, verse: 1, text: "A soft answer turneth away wrath: but grievous words stir up anger."),
    VerseOfTheDayEntry(dayOfYear: 228, bookName: "Proverbs", chapter: 16, verse: 18, text: "Pride goeth before destruction, and an haughty spirit before a fall."),
    VerseOfTheDayEntry(dayOfYear: 229, bookName: "Proverbs", chapter: 17, verse: 22, text: "A merry heart doeth good like a medicine: but a broken spirit drieth the bones."),
    VerseOfTheDayEntry(dayOfYear: 230, bookName: "Proverbs", chapter: 19, verse: 11, text: "The discretion of a man deferreth his anger; and it is his glory to pass over a transgression."),
    VerseOfTheDayEntry(dayOfYear: 231, bookName: "Proverbs", chapter: 21, verse: 21, text: "He that followeth after righteousness and mercy findeth life, righteousness, and honour."),
    VerseOfTheDayEntry(dayOfYear: 232, bookName: "Proverbs", chapter: 23, verse: 26, text: "My son, give me thine heart, and let thine eyes observe my ways."),
    VerseOfTheDayEntry(dayOfYear: 233, bookName: "Proverbs", chapter: 24, verse: 16, text: "For a just man falleth seven times, and riseth up again: but the wicked shall fall into mischief."),
    VerseOfTheDayEntry(dayOfYear: 234, bookName: "Proverbs", chapter: 25, verse: 11, text: "A word fitly spoken is like apples of gold in pictures of silver."),
    VerseOfTheDayEntry(dayOfYear: 235, bookName: "Proverbs", chapter: 27, verse: 1, text: "Boast not thyself of to morrow; for thou knowest not what a day may bring forth."),
    VerseOfTheDayEntry(dayOfYear: 236, bookName: "Proverbs", chapter: 28, verse: 1, text: "The wicked flee when no man pursueth: but the righteous are bold as a lion."),
    VerseOfTheDayEntry(dayOfYear: 237, bookName: "Proverbs", chapter: 29, verse: 25, text: "The fear of man bringeth a snare: but whoso putteth his trust in the LORD shall be safe."),
    VerseOfTheDayEntry(dayOfYear: 238, bookName: "Ecclesiastes", chapter: 12, verse: 13, text: "Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man."),
    VerseOfTheDayEntry(dayOfYear: 239, bookName: "Isaiah", chapter: 1, verse: 18, text: "Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool."),
    VerseOfTheDayEntry(dayOfYear: 240, bookName: "Isaiah", chapter: 6, verse: 8, text: "Also I heard the voice of the Lord, saying, Whom shall I send, and who will go for us? Then said I, Here am I; send me."),
    VerseOfTheDayEntry(dayOfYear: 241, bookName: "Isaiah", chapter: 9, verse: 2, text: "The people that walked in darkness have seen a great light: they that dwell in the land of the shadow of death, upon them hath the light shined."),
    VerseOfTheDayEntry(dayOfYear: 242, bookName: "Isaiah", chapter: 26, verse: 3, text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee."),
    VerseOfTheDayEntry(dayOfYear: 243, bookName: "Isaiah", chapter: 40, verse: 28, text: "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary? there is no searching of his understanding."),
    // ── September: OT Prophets ────────────────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 244, bookName: "Isaiah", chapter: 40, verse: 29, text: "He giveth power to the faint; and to them that have no might he increaseth strength."),
    VerseOfTheDayEntry(dayOfYear: 245, bookName: "Isaiah", chapter: 43, verse: 1, text: "But now thus saith the LORD that created thee, O Jacob, and he that formed thee, O Israel, Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine."),
    VerseOfTheDayEntry(dayOfYear: 246, bookName: "Isaiah", chapter: 43, verse: 2, text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee: when thou walkest through the fire, thou shalt not be burned; neither shall the flame kindle upon thee."),
    VerseOfTheDayEntry(dayOfYear: 247, bookName: "Isaiah", chapter: 44, verse: 6, text: "Thus saith the LORD the King of Israel, and his redeemer the LORD of hosts; I am the first, and I am the last; and beside me there is no God."),
    VerseOfTheDayEntry(dayOfYear: 248, bookName: "Isaiah", chapter: 45, verse: 22, text: "Look unto me, and be ye saved, all the ends of the earth: for I am God, and there is none else."),
    VerseOfTheDayEntry(dayOfYear: 249, bookName: "Isaiah", chapter: 48, verse: 17, text: "Thus saith the LORD, thy Redeemer, the Holy One of Israel; I am the LORD thy God which teacheth thee to profit, which leadeth thee by the way that thou shouldest go."),
    VerseOfTheDayEntry(dayOfYear: 250, bookName: "Isaiah", chapter: 54, verse: 10, text: "For the mountains shall depart, and the hills be removed; but my kindness shall not depart from thee, neither shall the covenant of my peace be removed, saith the LORD that hath mercy on thee."),
    VerseOfTheDayEntry(dayOfYear: 251, bookName: "Isaiah", chapter: 55, verse: 6, text: "Seek ye the LORD while he may be found, call ye upon him while he is near:"),
    VerseOfTheDayEntry(dayOfYear: 252, bookName: "Isaiah", chapter: 55, verse: 8, text: "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD."),
    VerseOfTheDayEntry(dayOfYear: 253, bookName: "Isaiah", chapter: 55, verse: 11, text: "So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it."),
    VerseOfTheDayEntry(dayOfYear: 254, bookName: "Isaiah", chapter: 61, verse: 1, text: "The Spirit of the Lord GOD is upon me; because the LORD hath anointed me to preach good tidings unto the meek; he hath sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to them that are bound;"),
    VerseOfTheDayEntry(dayOfYear: 255, bookName: "Isaiah", chapter: 64, verse: 8, text: "But now, O LORD, thou art our father; we are the clay, and thou our potter; and we all are the work of thy hand."),
    VerseOfTheDayEntry(dayOfYear: 256, bookName: "Jeremiah", chapter: 17, verse: 7, text: "Blessed is the man that trusteth in the LORD, and whose hope the LORD is."),
    VerseOfTheDayEntry(dayOfYear: 257, bookName: "Jeremiah", chapter: 17, verse: 8, text: "For he shall be as a tree planted by the waters, and that spreadeth out her roots by the river, and shall not see when heat cometh, but her leaf shall be green; and shall not be careful in the year of drought, neither shall cease from yielding fruit."),
    VerseOfTheDayEntry(dayOfYear: 258, bookName: "Jeremiah", chapter: 33, verse: 3, text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not."),
    VerseOfTheDayEntry(dayOfYear: 259, bookName: "Lamentations", chapter: 3, verse: 22, text: "It is of the LORD'S mercies that we are not consumed, because his compassions fail not."),
    VerseOfTheDayEntry(dayOfYear: 260, bookName: "Lamentations", chapter: 3, verse: 25, text: "The LORD is good unto them that wait for him, to the soul that seeketh him."),
    VerseOfTheDayEntry(dayOfYear: 261, bookName: "Ezekiel", chapter: 36, verse: 26, text: "A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh."),
    VerseOfTheDayEntry(dayOfYear: 262, bookName: "Daniel", chapter: 3, verse: 17, text: "If it be so, our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of thine hand, O king."),
    VerseOfTheDayEntry(dayOfYear: 263, bookName: "Hosea", chapter: 6, verse: 3, text: "Then shall we know, if we follow on to know the LORD: his going forth is prepared as the morning; and he shall come unto us as the rain, as the latter and former rain unto the earth."),
    VerseOfTheDayEntry(dayOfYear: 264, bookName: "Joel", chapter: 2, verse: 25, text: "And I will restore to you the years that the locust hath eaten, the cankerworm, and the caterpiller, and the palmerworm, my great army which I sent among you."),
    VerseOfTheDayEntry(dayOfYear: 265, bookName: "Joel", chapter: 2, verse: 32, text: "And it shall come to pass, that whosoever shall call on the name of the LORD shall be delivered: for in mount Zion and in Jerusalem shall be deliverance, as the LORD hath said, and in the remnant whom the LORD shall call."),
    VerseOfTheDayEntry(dayOfYear: 266, bookName: "Amos", chapter: 5, verse: 24, text: "But let judgment run down as waters, and righteousness as a mighty stream."),
    VerseOfTheDayEntry(dayOfYear: 267, bookName: "Jonah", chapter: 2, verse: 9, text: "But I will sacrifice unto thee with the voice of thanksgiving; I will pay that that I have vowed. Salvation is of the LORD."),
    VerseOfTheDayEntry(dayOfYear: 268, bookName: "Micah", chapter: 6, verse: 8, text: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?"),
    VerseOfTheDayEntry(dayOfYear: 269, bookName: "Habakkuk", chapter: 3, verse: 19, text: "The LORD God is my strength, and he will make my feet like hinds' feet, and he will make me to walk upon mine high places."),
    VerseOfTheDayEntry(dayOfYear: 270, bookName: "Nahum", chapter: 1, verse: 7, text: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him."),
    VerseOfTheDayEntry(dayOfYear: 271, bookName: "Malachi", chapter: 3, verse: 10, text: "Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it."),
    VerseOfTheDayEntry(dayOfYear: 272, bookName: "Matthew", chapter: 28, verse: 19, text: "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:"),
    VerseOfTheDayEntry(dayOfYear: 273, bookName: "Matthew", chapter: 28, verse: 20, text: "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen."),
    // ── October: NT Letters & Great Commission ────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 274, bookName: "Mark", chapter: 12, verse: 30, text: "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment."),
    VerseOfTheDayEntry(dayOfYear: 275, bookName: "Mark", chapter: 12, verse: 31, text: "And the second is like, namely this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these."),
    VerseOfTheDayEntry(dayOfYear: 276, bookName: "Luke", chapter: 1, verse: 37, text: "For with God nothing shall be impossible."),
    VerseOfTheDayEntry(dayOfYear: 277, bookName: "Luke", chapter: 2, verse: 14, text: "Glory to God in the highest, and on earth peace, good will toward men."),
    VerseOfTheDayEntry(dayOfYear: 278, bookName: "John", chapter: 1, verse: 1, text: "In the beginning was the Word, and the Word was with God, and the Word was God."),
    VerseOfTheDayEntry(dayOfYear: 279, bookName: "John", chapter: 1, verse: 14, text: "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth."),
    VerseOfTheDayEntry(dayOfYear: 280, bookName: "John", chapter: 3, verse: 17, text: "For God sent not his Son into the world to condemn the world; but that the world through him might be saved."),
    VerseOfTheDayEntry(dayOfYear: 281, bookName: "John", chapter: 4, verse: 14, text: "But whosoever drinketh of the water that I shall give him shall never thirst; but the water that I shall give him shall be in him a well of water springing up into everlasting life."),
    VerseOfTheDayEntry(dayOfYear: 282, bookName: "John", chapter: 4, verse: 24, text: "God is a Spirit: and they that worship him must worship him in spirit and in truth."),
    VerseOfTheDayEntry(dayOfYear: 283, bookName: "John", chapter: 6, verse: 35, text: "And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst."),
    VerseOfTheDayEntry(dayOfYear: 284, bookName: "John", chapter: 8, verse: 31, text: "Then said Jesus to those Jews which believed on him, If ye continue in my word, then are ye my disciples indeed;"),
    VerseOfTheDayEntry(dayOfYear: 285, bookName: "John", chapter: 8, verse: 32, text: "And ye shall know the truth, and the truth shall make you free."),
    VerseOfTheDayEntry(dayOfYear: 286, bookName: "John", chapter: 14, verse: 1, text: "Let not your heart be troubled: ye believe in God, believe also in me."),
    VerseOfTheDayEntry(dayOfYear: 287, bookName: "John", chapter: 14, verse: 2, text: "In my Father's house are many mansions: if it were not so, I would have told you. I go to prepare a place for you."),
    VerseOfTheDayEntry(dayOfYear: 288, bookName: "John", chapter: 14, verse: 27, text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid."),
    VerseOfTheDayEntry(dayOfYear: 289, bookName: "John", chapter: 17, verse: 17, text: "Sanctify them through thy truth: thy word is truth."),
    VerseOfTheDayEntry(dayOfYear: 290, bookName: "John", chapter: 21, verse: 17, text: "He saith unto him the third time, Simon, son of Jonas, lovest thou me? Peter was grieved because he said unto him the third time, Lovest thou me? And he said unto him, Lord, thou knowest all things; thou knowest that I love thee. Jesus saith unto him, Feed my sheep."),
    VerseOfTheDayEntry(dayOfYear: 291, bookName: "Acts", chapter: 2, verse: 42, text: "And they continued stedfastly in the apostles' doctrine and fellowship, and in breaking of bread, and in prayers."),
    VerseOfTheDayEntry(dayOfYear: 292, bookName: "Acts", chapter: 17, verse: 28, text: "For in him we live, and move, and have our being; as certain also of your own poets have said, For we are also his offspring."),
    VerseOfTheDayEntry(dayOfYear: 293, bookName: "Romans", chapter: 12, verse: 1, text: "I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service."),
    VerseOfTheDayEntry(dayOfYear: 294, bookName: "Romans", chapter: 12, verse: 10, text: "Be kindly affectioned one to another with brotherly love; in honour preferring one another;"),
    VerseOfTheDayEntry(dayOfYear: 295, bookName: "Romans", chapter: 12, verse: 21, text: "Be not overcome of evil, but overcome evil with good."),
    VerseOfTheDayEntry(dayOfYear: 296, bookName: "Romans", chapter: 15, verse: 13, text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost."),
    VerseOfTheDayEntry(dayOfYear: 297, bookName: "1 Corinthians", chapter: 13, verse: 13, text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity."),
    VerseOfTheDayEntry(dayOfYear: 298, bookName: "1 Corinthians", chapter: 16, verse: 13, text: "Watch ye, stand fast in the faith, quit you like men, be strong."),
    VerseOfTheDayEntry(dayOfYear: 299, bookName: "2 Corinthians", chapter: 5, verse: 7, text: "For we walk by faith, not by sight:"),
    VerseOfTheDayEntry(dayOfYear: 300, bookName: "Galatians", chapter: 3, verse: 28, text: "There is neither Jew nor Greek, there is neither bond nor free, there is neither male nor female: for ye are all one in Christ Jesus."),
    VerseOfTheDayEntry(dayOfYear: 301, bookName: "Ephesians", chapter: 2, verse: 10, text: "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them."),
    VerseOfTheDayEntry(dayOfYear: 302, bookName: "Ephesians", chapter: 3, verse: 17, text: "That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love,"),
    VerseOfTheDayEntry(dayOfYear: 303, bookName: "Ephesians", chapter: 3, verse: 19, text: "And to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God."),
    VerseOfTheDayEntry(dayOfYear: 304, bookName: "Philippians", chapter: 2, verse: 5, text: "Let this mind be in you, which was also in Christ Jesus:"),
    // ── November: Thanksgiving & Praise ──────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 305, bookName: "Psalms", chapter: 107, verse: 1, text: "O give thanks unto the LORD, for he is good: for his mercy endureth for ever."),
    VerseOfTheDayEntry(dayOfYear: 306, bookName: "Psalms", chapter: 107, verse: 15, text: "Oh that men would praise the LORD for his goodness, and for his wonderful works to the children of men!"),
    VerseOfTheDayEntry(dayOfYear: 307, bookName: "Psalms", chapter: 118, verse: 1, text: "O give thanks unto the LORD; for he is good: because his mercy endureth for ever."),
    VerseOfTheDayEntry(dayOfYear: 308, bookName: "Psalms", chapter: 136, verse: 1, text: "O give thanks unto the LORD; for he is good: for his mercy endureth for ever."),
    VerseOfTheDayEntry(dayOfYear: 309, bookName: "Philippians", chapter: 4, verse: 4, text: "Rejoice in the Lord alway: and again I say, Rejoice."),
    VerseOfTheDayEntry(dayOfYear: 310, bookName: "Philippians", chapter: 4, verse: 11, text: "Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content."),
    VerseOfTheDayEntry(dayOfYear: 311, bookName: "Colossians", chapter: 3, verse: 15, text: "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful."),
    VerseOfTheDayEntry(dayOfYear: 312, bookName: "Colossians", chapter: 3, verse: 17, text: "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him."),
    VerseOfTheDayEntry(dayOfYear: 313, bookName: "2 Thessalonians", chapter: 3, verse: 3, text: "But the Lord is faithful, who shall stablish you, and keep you from evil."),
    VerseOfTheDayEntry(dayOfYear: 314, bookName: "1 Timothy", chapter: 4, verse: 4, text: "For every creature of God is good, and nothing to be refused, if it be received with thanksgiving:"),
    VerseOfTheDayEntry(dayOfYear: 315, bookName: "Hebrews", chapter: 13, verse: 15, text: "By him therefore let us offer the sacrifice of praise to God continually, that is, the fruit of our lips giving thanks to his name."),
    VerseOfTheDayEntry(dayOfYear: 316, bookName: "Revelation", chapter: 7, verse: 12, text: "Saying, Amen: Blessing, and glory, and wisdom, and thanksgiving, and honour, and power, and might, be unto our God for ever and ever. Amen."),
    VerseOfTheDayEntry(dayOfYear: 317, bookName: "Psalms", chapter: 9, verse: 1, text: "I will praise thee, O LORD, with my whole heart; I will shew forth all thy marvellous works."),
    VerseOfTheDayEntry(dayOfYear: 318, bookName: "Psalms", chapter: 28, verse: 7, text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him."),
    VerseOfTheDayEntry(dayOfYear: 319, bookName: "Psalms", chapter: 50, verse: 23, text: "Whoso offereth praise glorifieth me: and to him that ordereth his conversation aright will I shew the salvation of God."),
    VerseOfTheDayEntry(dayOfYear: 320, bookName: "Psalms", chapter: 69, verse: 30, text: "I will praise the name of God with a song, and will magnify him with thanksgiving."),
    VerseOfTheDayEntry(dayOfYear: 321, bookName: "Psalms", chapter: 75, verse: 1, text: "Unto thee, O God, do we give thanks, unto thee do we give thanks: for that thy name is near thy wondrous works declare."),
    VerseOfTheDayEntry(dayOfYear: 322, bookName: "Psalms", chapter: 95, verse: 1, text: "O come, let us sing unto the LORD: let us make a joyful noise to the rock of our salvation."),
    VerseOfTheDayEntry(dayOfYear: 323, bookName: "Psalms", chapter: 96, verse: 1, text: "O sing unto the LORD a new song: sing unto the LORD, all the earth."),
    VerseOfTheDayEntry(dayOfYear: 324, bookName: "Psalms", chapter: 98, verse: 1, text: "O sing unto the LORD a new song; for he hath done marvellous things: his right hand, and his holy arm, hath gotten him the victory."),
    VerseOfTheDayEntry(dayOfYear: 325, bookName: "Psalms", chapter: 105, verse: 1, text: "O give thanks unto the LORD; call upon his name: make known his deeds among the people."),
    VerseOfTheDayEntry(dayOfYear: 326, bookName: "Psalms", chapter: 105, verse: 4, text: "Seek the LORD, and his strength: seek his face evermore."),
    VerseOfTheDayEntry(dayOfYear: 327, bookName: "Psalms", chapter: 106, verse: 1, text: "Praise ye the LORD. O give thanks unto the LORD; for he is good: for his mercy endureth for ever."),
    VerseOfTheDayEntry(dayOfYear: 328, bookName: "Psalms", chapter: 111, verse: 2, text: "The works of the LORD are great, sought out of all them that have pleasure therein."),
    VerseOfTheDayEntry(dayOfYear: 329, bookName: "Psalms", chapter: 111, verse: 10, text: "The fear of the LORD is the beginning of wisdom: a good understanding have all they that do his commandments: his praise endureth for ever."),
    VerseOfTheDayEntry(dayOfYear: 330, bookName: "Psalms", chapter: 113, verse: 3, text: "From the rising of the sun unto the going down of the same the LORD'S name is to be praised."),
    VerseOfTheDayEntry(dayOfYear: 331, bookName: "Psalms", chapter: 117, verse: 2, text: "For his merciful kindness is great toward us: and the truth of the LORD endureth for ever. Praise ye the LORD."),
    VerseOfTheDayEntry(dayOfYear: 332, bookName: "Psalms", chapter: 119, verse: 62, text: "At midnight I will rise to give thanks unto thee because of thy righteous judgments."),
    VerseOfTheDayEntry(dayOfYear: 333, bookName: "Psalms", chapter: 119, verse: 89, text: "For ever, O LORD, thy word is settled in heaven."),
    VerseOfTheDayEntry(dayOfYear: 334, bookName: "Psalms", chapter: 119, verse: 164, text: "Seven times a day do I praise thee because of thy righteous judgments."),
    // ── December 1–23: Advent ─────────────────────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 335, bookName: "Isaiah", chapter: 7, verse: 14, text: "Therefore the Lord himself shall give you a sign; Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel."),
    VerseOfTheDayEntry(dayOfYear: 336, bookName: "Isaiah", chapter: 9, verse: 6, text: "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace."),
    VerseOfTheDayEntry(dayOfYear: 337, bookName: "Isaiah", chapter: 9, verse: 7, text: "Of the increase of his government and peace there shall be no end, upon the throne of David, and upon his kingdom, to order it, and to establish it with judgment and with justice from henceforth even for ever."),
    VerseOfTheDayEntry(dayOfYear: 338, bookName: "Isaiah", chapter: 11, verse: 1, text: "And there shall come forth a rod out of the stem of Jesse, and a Branch shall grow out of his roots:"),
    VerseOfTheDayEntry(dayOfYear: 339, bookName: "Isaiah", chapter: 11, verse: 2, text: "And the spirit of the LORD shall rest upon him, the spirit of wisdom and understanding, the spirit of counsel and might, the spirit of knowledge and of the fear of the LORD;"),
    VerseOfTheDayEntry(dayOfYear: 340, bookName: "Isaiah", chapter: 40, verse: 3, text: "The voice of him that crieth in the wilderness, Prepare ye the way of the LORD, make straight in the desert a highway for our God."),
    VerseOfTheDayEntry(dayOfYear: 341, bookName: "Isaiah", chapter: 40, verse: 5, text: "And the glory of the LORD shall be revealed, and all flesh shall see it together: for the mouth of the LORD hath spoken it."),
    VerseOfTheDayEntry(dayOfYear: 342, bookName: "Micah", chapter: 5, verse: 2, text: "But thou, Bethlehem Ephratah, though thou be little among the thousands of Judah, yet out of thee shall he come forth unto me that is to be ruler in Israel; whose goings forth have been from of old, from everlasting."),
    VerseOfTheDayEntry(dayOfYear: 343, bookName: "Zechariah", chapter: 2, verse: 10, text: "Sing and rejoice, O daughter of Zion: for, lo, I come, and I will dwell in the midst of thee, saith the LORD."),
    VerseOfTheDayEntry(dayOfYear: 344, bookName: "Malachi", chapter: 4, verse: 2, text: "But unto you that fear my name shall the Sun of righteousness arise with healing in his wings; and ye shall go forth, and grow up as calves of the stall."),
    VerseOfTheDayEntry(dayOfYear: 345, bookName: "Luke", chapter: 1, verse: 26, text: "And in the sixth month the angel Gabriel was sent from God unto a city of Galilee, named Nazareth,"),
    VerseOfTheDayEntry(dayOfYear: 346, bookName: "Luke", chapter: 1, verse: 30, text: "And the angel said unto her, Fear not, Mary: for thou hast found favour with God."),
    VerseOfTheDayEntry(dayOfYear: 347, bookName: "Luke", chapter: 1, verse: 31, text: "And, behold, thou shalt conceive in thy womb, and bring forth a son, and shalt call his name JESUS."),
    VerseOfTheDayEntry(dayOfYear: 348, bookName: "Luke", chapter: 1, verse: 35, text: "And the angel answered and said unto her, The Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee: therefore also that holy thing which shall be born of thee shall be called the Son of God."),
    VerseOfTheDayEntry(dayOfYear: 349, bookName: "Luke", chapter: 1, verse: 38, text: "And Mary said, Behold the handmaid of the Lord; be it unto me according to thy word. And the angel departed from her."),
    VerseOfTheDayEntry(dayOfYear: 350, bookName: "Luke", chapter: 1, verse: 46, text: "And Mary said, My soul doth magnify the Lord,"),
    VerseOfTheDayEntry(dayOfYear: 351, bookName: "Luke", chapter: 1, verse: 78, text: "Through the tender mercy of our God; whereby the dayspring from on high hath visited us,"),
    VerseOfTheDayEntry(dayOfYear: 352, bookName: "Matthew", chapter: 1, verse: 18, text: "Now the birth of Jesus Christ was on this wise: When as his mother Mary was espoused to Joseph, before they came together, she was found with child of the Holy Ghost."),
    VerseOfTheDayEntry(dayOfYear: 353, bookName: "Matthew", chapter: 1, verse: 23, text: "Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us."),
    VerseOfTheDayEntry(dayOfYear: 354, bookName: "John", chapter: 1, verse: 9, text: "That was the true Light, which lighteth every man that cometh into the world."),
    VerseOfTheDayEntry(dayOfYear: 355, bookName: "John", chapter: 1, verse: 11, text: "He came unto his own, and his own received him not."),
    VerseOfTheDayEntry(dayOfYear: 356, bookName: "John", chapter: 1, verse: 12, text: "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:"),
    VerseOfTheDayEntry(dayOfYear: 357, bookName: "John", chapter: 1, verse: 13, text: "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God."),
    VerseOfTheDayEntry(dayOfYear: 358, bookName: "Romans", chapter: 5, verse: 6, text: "For when we were yet without strength, in due time Christ died for the ungodly."),
    // ── December 24–31: Christmas & Year's End ────────────────────────────────────
    VerseOfTheDayEntry(dayOfYear: 359, bookName: "Luke", chapter: 2, verse: 11, text: "For unto you is born this day in the city of David a Saviour, which is Christ the Lord."),
    VerseOfTheDayEntry(dayOfYear: 360, bookName: "Luke", chapter: 2, verse: 10, text: "And the angel said unto them, Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people."),
    VerseOfTheDayEntry(dayOfYear: 361, bookName: "Matthew", chapter: 2, verse: 11, text: "And when they were come into the house, they saw the young child with Mary his mother, and fell down, and worshipped him: and when they had opened their treasures, they presented unto him gifts; gold, and frankincense, and myrrh."),
    VerseOfTheDayEntry(dayOfYear: 362, bookName: "John", chapter: 3, verse: 3, text: "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God."),
    VerseOfTheDayEntry(dayOfYear: 363, bookName: "Galatians", chapter: 4, verse: 4, text: "But when the fulness of the time was come, God sent forth his Son, made of a woman, made under the law,"),
    VerseOfTheDayEntry(dayOfYear: 364, bookName: "1 John", chapter: 4, verse: 9, text: "In this was manifested the love of God toward us, because that God sent his only begotten Son into the world, that we might live through him."),
    VerseOfTheDayEntry(dayOfYear: 365, bookName: "Psalms", chapter: 90, verse: 12, text: "So teach us to number our days, that we may apply our hearts unto wisdom."),
    VerseOfTheDayEntry(dayOfYear: 366, bookName: "Revelation", chapter: 21, verse: 5, text: "And he that sat upon the throne said, Behold, I make all things new. And he said unto me, Write: for these words are true and faithful."),
]
